version: "3.2"
services:
  ckanextgeodatagov:
    image: openknowledge/ckan-dev:2.8
    env_file:
      - .env
    links:
      - db
      - solr
      - redis
      - datapusher
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ckan_storage:/var/lib/ckan
  db:
    image: ckan/postgresql
    expose:
      - "5432"
  solr:
    image: ckan/solr
    restart: always
    expose:
      - "8983"
  datapusher:
    image: keitaro/ckan-datapusher
    ports:
      - "8800:8800"
  redis:
    image: redis:alpine
  
volumes:
  ckan_storage:
  pg_data:
  solr_data: