---
version: "3.7"
services:
  app:
    image: datagov/ckanext-geodatagov:${CKAN_VERSION} # ensures docker-compose will rebuild the right image in case we change CKAN_VERSION
    build:
      context: .
      args:
        CKAN_VERSION: ${CKAN_VERSION}
    env_file:
      - .env
    environment:
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1
      CKAN_DATAPUSHER_URL: http://localhost:8080/  # datapusher is not really enabled
      PYTHONDONTWRITEBYTECODE: 1
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
      - solr
    volumes:
      - ./ckanext:/srv/app/ckanext/
      - ./test.sh:/srv/app/test.sh
      - ./test.ini:/srv/app/test.ini
      - ./setup.py:/srv/app/setup.py
      - ckan_storage:/var/lib/ckan
      - ./docker-entrypoint.d:/docker-entrypoint.d

  db:
    image: datagov/catalog.data.gov.db:latest
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready --username=postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  solr:
    image: datagov/catalog.data.gov.solr:latest
    ports:
      - "8983:8983"

  localstack-container:
    container_name: "localstack-container"
    privileged: true
    image: localstack/localstack:1.1.0
    ports:
      - "4566-4583:4566-4583"
      - "8081:8081"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - HOSTNAME=
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
      - START_WEB=1
    volumes:
      - "./tmp/localstack:/var/lib/localstack"
      - "./tmp/localstack/run/docker.sock:/var/run/docker.sock"

volumes:
  ckan_storage:
  pg_data:
  solr_data:
