version: "3.2"
services:
  ckan:
    build: 
      context: ckan-docker
    env_file:
      - .env
    depends_on:
      - db
      - solr
      - redis
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    volumes:
      - ckan_storage:/var/lib/ckan
      - .:/srv/app/src_extensions/geodatagov
  db:
    image: ckan/postgresql
    expose:
      - "5432"
  solr:
    image: ckan/solr
    restart: always
    expose:
      - "8983"
  redis:
    image: redis:alpine
  
volumes:
  ckan_storage:
  pg_data:
  solr_data: