---
version: "3.7"
services:
  app:
    image: datagov/ckanext-geodatagov:${CKAN_VERSION} # ensures docker-compose will rebuild the right image in case we change CKAN_VERSION
    build:
      context: .
      args:
        CKAN_VERSION: ${CKAN_VERSION}
    env_file:
      - .env
    environment:
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@db/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@db/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@db/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1
      CKAN_DATAPUSHER_URL: http://localhost:8080/  # datapusher is not really enabled
      CKAN__PLUGINS: datajson harvest datajson_harvest
      PYTHONDONTWRITEBYTECODE: 1
    working_dir: /app
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
      - solr
    volumes:
      - .:/app
      - ckan_storage:/var/lib/ckan
      - .:/srv/app/src_extensions/geodatagov
  db:
    image: ckan/ckan-postgres-dev:${CKAN_VERSION}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
  solr:
    image: ckan/ckan-solr-dev:${CKAN_VERSION}
    ports:
      - "8983:8983"

volumes:
  ckan_storage:
  pg_data:
  solr_data:
